name: Qlarissa
channels:
  - conda-forge
dependencies:
  - blinker=1.9.0=pyhff2d567_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - flask=3.1.2=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsqlite=3.51.1=hf5d6505_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mkl=2025.3.0=hac47afa_454
  - numpy=2.4.0=py314h06c3c77_0
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.2=h4b44e0e_100_cp314
  - python_abi=3.14=8_cp314
  - scipy=1.16.3=py314h221f224_2
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - werkzeug=3.1.4=pyhcf101f3_0
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=h534d264_6
  - pip:
    - beautifulsoup4==4.14.3
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - curl_cffi==0.13.0
    - frozendict==2.4.7
    - idna==3.11
    - multitasking==0.0.12
    - pandas==2.3.3
    - peewee==3.18.3
    - platformdirs==4.5.1
    - protobuf==6.33.2
    - pycparser==2.23
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - six==1.17.0
    - soupsieve==2.8.1
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.2
    - websockets==15.0.1
    - yfinance==1.0

prefix: "G:\\Applications\\miniforge3\\envs\\Qlarissa"
